name: 'retail_scd'
version: '1.0'

config-version: 2

profile: 'retail_scd'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  retail_scd:
    dimensions:
      +materialized: table
